#ifndef TRANSNAMES_H
#define TRANSNAMES_H

/**
* dockBar组件显示名称定义
*/
#define APP_DOCK_BAR_TRANS_NAMES_LOGO_LABEL ":/images/16"
#define APP_DOCK_BAR_TRANS_NAMES_TITLE_LABEL "  Markplus"
#define APP_DOCK_BAR_TRANS_NAMES_TEXT_LABEL ""
#define APP_DOCK_BAR_TRANS_NAMES_MINIM_BUTTON "-"
#define APP_DOCK_BAR_TRANS_NAMES_MAXIM_BUTTON "口"
#define APP_DOCK_BAR_TRANS_NAMES_CLOSE_BUTTON "X"
#define APP_DOCK_BAR_TRANS_NAMES_SETTING_BUTTON "S"

#endif // TRANSNAMES_H
